# Stage 1: Build
FROM golang:1.21.3-alpine3.18 AS builder
WORKDIR /service
COPY . .
# Ensure that the go.mod file is present in the ./service directory
# If not using Go modules, comment out the next line
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -a -o api .

# Stage 2: Run
FROM alpine:3.18.4
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /service/api .
EXPOSE 8080
CMD ["./api"]
