// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cycles": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Insert new Cycles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cycle"
                ],
                "summary": "InsertOne",
                "operationId": "InsertOneCycle",
                "parameters": [
                    {
                        "description": "Cycle input Object",
                        "name": "reqJson",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cycle.CycleInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cycle.CycleDisplay"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/cycles/email/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Cycles by from User email (In context)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cycle"
                ],
                "summary": "GetFromUserEmail",
                "operationId": "GetFromUserEmail",
                "responses": {
                    "200": {
                        "description": "Cycle retrieved successfully.",
                        "schema": {
                            "$ref": "#/definitions/cycle.CycleDisplay"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or data missing.",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Authorization failed. Please provide a valid token.",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "Cycle not found with the specified ID.",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "An internal server error occurred while processing the request.",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/cycles/email/{status}/{page}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Cycles by sending status and page and receiver email (in context)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cycle"
                ],
                "summary": "GetAllFromReceiverEmail",
                "operationId": "GetAllFromReceiverEmail",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cycle.CycleDisplay"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/cycles/goal": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Inserts Hard Skills into the existing cycle for the specified user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cycle"
                ],
                "summary": "Update Hard Skills for a User's Active Cycle",
                "operationId": "UpdateHardSkillsByEmail",
                "parameters": [
                    {
                        "description": "Hard Skills input",
                        "name": "reqJson",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cycle.UpdateGoalSkillsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "Error marshaling JSON or mismatched goal score",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "Cycle not found",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/cycles/progress/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Cycle with status On progress",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cycle"
                ],
                "summary": "GetCycleProgess",
                "operationId": "GetCycleProgess",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cycle Id",
                        "name": "cycleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "nil",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "invalid cycle id",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "cycle not found",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/cycles/update/{id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update user score by Score in cycle.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cycle"
                ],
                "summary": "UpdateUserFinalScore",
                "operationId": "UpdateUserFinalScore",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CycleId",
                        "name": "cycleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "nil",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "invalid cycle id",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "cycle not found",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/cycles/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a cycle by its unique identifier.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cycle"
                ],
                "summary": "Get a cycle by ID",
                "operationId": "GetOneCycleByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cycle ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cycle retrieved successfully.",
                        "schema": {
                            "$ref": "#/definitions/cycle.Cycle"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or data missing.",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Authorization failed. Please provide a valid token.",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "Cycle not found with the specified ID.",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "An internal server error occurred while processing the request.",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update cycle with specific ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cycle"
                ],
                "summary": "UpdateByID",
                "operationId": "UpdateByID",
                "parameters": [
                    {
                        "description": "Cycle input Object",
                        "name": "reqJson",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cycle.Cycle"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cycle.CycleDisplay"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete Cycles by cycles ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cycle"
                ],
                "summary": "DeleteByID",
                "operationId": "DeleteByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Squad ID",
                        "name": "squadID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "nil",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "400": {
                        "description": "invalid cycle id",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "cycle not found",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/member-squads/members": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add member to squad",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "membersquad"
                ],
                "summary": "AddMemberSquad",
                "operationId": "AddMemberSquad",
                "parameters": [
                    {
                        "description": "SquadMember Object",
                        "name": "s",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/membersquad.SquadMember"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/member-squads/{squadID}/members": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete all member from squad (at least 1 member in squad)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "membersquad"
                ],
                "summary": "DeleteMemberSquad",
                "operationId": "DeleteMemberSquad",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Squad ID",
                        "name": "squadID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get user by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "GetUserByID",
                "operationId": "GetUserByID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.GetUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "405": {
                        "description": "Store Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update user profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "UpdateUser",
                "operationId": "UpdateUser",
                "parameters": [
                    {
                        "description": "Editable object",
                        "name": "reqJson",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.aboutme"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "405": {
                        "description": "Store Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/profile/skills": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get skill by user id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "GetSkillsByUserID",
                "operationId": "GetSkillsByUserID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kind of skill [soft , technical]",
                        "name": "kind",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.GetSkillByUserIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "405": {
                        "description": "Store Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/profile/skills/soft": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update user soft skills",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "UpdateSoftSkills",
                "operationId": "UpdateSoftSkills",
                "parameters": [
                    {
                        "description": "List of user soft skills",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/profile.Skill"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "405": {
                        "description": "Store Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/profile/skills/technical": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update user technical skills",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "UpdateTechnicalSkills",
                "operationId": "UpdateTechnicalSkills",
                "parameters": [
                    {
                        "description": "List of user technical skills",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/profile.Skill"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "405": {
                        "description": "Store Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/profile/squad/{squadID}/skill-ratings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get one squad with a user skill ratings in that squad",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "GetUserSkillRatingBySquadID",
                "operationId": "GetUserSkillRatingBySquadID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Squad ID",
                        "name": "squadID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/profile.mySkillRateInSquadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Rate every skills",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "RateSkills",
                "operationId": "RateSkills",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Squad ID",
                        "name": "squadID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rate Skill",
                        "name": "rateSkill",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.RateSkill"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/squad.Squad"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/skills": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all skill or all of that kind of skill",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "skill"
                ],
                "summary": "GetSkillsByKind",
                "operationId": "GetSkillsByKind",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kind of skill [soft , technical]",
                        "name": "kind",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/skill.Skill"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "405": {
                        "description": "Store Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/skills/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a skill by skill id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "skill"
                ],
                "summary": "GetSkillByID",
                "operationId": "GetSkillByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Skill ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/skill.Skill"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "405": {
                        "description": "Store Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/squads": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all squads",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "summary": "GetAll",
                "operationId": "GetAll",
                "parameters": [
                    {
                        "description": "Filter for squad",
                        "name": "squadFilter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/squad.SquadFilter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/squad.Squad"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a squad",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "summary": "InsertOneByID",
                "operationId": "InsertOneByID",
                "parameters": [
                    {
                        "description": "Squad object",
                        "name": "insert",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/squad.Squad"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/squad.Squad"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/squads/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get one squad by squad id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "summary": "GetOneByID",
                "operationId": "GetOneByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Squad ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/squad.Squad"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a squad",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "summary": "DeleteSquadByID",
                "operationId": "DeleteSquadByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Squad ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/squad.Squad"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/squads/{squadID}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update a squad when lead edit squad data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "summary": "UpdateOneByID",
                "operationId": "UpdateOneByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Squad ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Squad",
                        "name": "squad",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/squad.Squad"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/squad.Squad"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/squads/{squadID}/member-skills-avg": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Calculate squad member average per skill",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "summary": "CalculateSquadMemberAveragePerSkill",
                "operationId": "CalculateSquadMemberAveragePerSkill",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Squad ID",
                        "name": "squadID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/squad.SquadAverageSkillOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/squads/{squadID}/skills-require-avg": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get one squad with average skill ratings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "squad"
                ],
                "summary": "GetAvgSkillRatingByID",
                "operationId": "GetAvgSkillRatingByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Squad ID",
                        "name": "squadID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/squad.SquadAverageSkillOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "405": {
                        "description": "Store Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get user profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "GetAllUsers",
                "operationId": "GetAllUsers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search name or email",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.GetUserResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "405": {
                        "description": "Store Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/users/:id": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches all team.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Retrieve all team name that Im member",
                "operationId": "GetMySquadThatImMemberByID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.GetEmailNameResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/users/email": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches all users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Retrieve all users' email and name",
                "operationId": "GetUsersData",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.GetEmailNameResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches all HardSkill.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Retrieve all HardSkill",
                "operationId": "GetHardSkillsMemberByID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.MyHardSkill"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/app.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/app.status"
                }
            }
        },
        "app.status": {
            "type": "string",
            "enum": [
                "success",
                "error"
            ],
            "x-enum-varnames": [
                "Success",
                "Fail"
            ]
        },
        "cycle.Cycle": {
            "type": "object",
            "required": [
                "endDate",
                "receiverMail",
                "senderMail",
                "startDate",
                "status"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "intuitiveSkill": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cycle.IntuitiveSkill"
                    }
                },
                "quantitativeSkill": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cycle.QuantitativeSkill"
                    }
                },
                "receiverMail": {
                    "type": "string"
                },
                "senderMail": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "cycle.CycleDisplay": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "intuitiveSkill": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cycle.IntuitiveSkill"
                    }
                },
                "quantitativeSkill": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cycle.QuantitativeSkillDisplay"
                    }
                },
                "receiverMail": {
                    "type": "string"
                },
                "senderMail": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "cycle.CycleInput": {
            "type": "object",
            "required": [
                "endDate",
                "quantitativeSkill",
                "receiverMail",
                "startDate"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "intuitiveSkill": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cycle.IntuitiveSkill"
                    }
                },
                "quantitativeSkill": {
                    "description": "QuantitiveSkill \u003e= 1 skill",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cycle.QuantitativeSkill"
                    }
                },
                "receiverMail": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                }
            }
        },
        "cycle.HardSkill": {
            "type": "object",
            "required": [
                "description",
                "goalScore",
                "name",
                "personalScore",
                "skillLevels"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "goalScore": {
                    "type": "integer"
                },
                "leadScore": {
                    "type": "integer"
                },
                "mutualScore": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "personalScore": {
                    "type": "integer"
                },
                "skillLevels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cycle.SkillLevel"
                    }
                }
            }
        },
        "cycle.IntuitiveSkill": {
            "type": "object",
            "required": [
                "goal",
                "name"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "goal": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "cycle.QuantitativeSkill": {
            "type": "object",
            "required": [
                "goalScore",
                "personalScore"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "finalScore": {
                    "type": "integer"
                },
                "goalScore": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "leadGoalScore": {
                    "type": "integer"
                },
                "personalScore": {
                    "type": "integer"
                }
            }
        },
        "cycle.QuantitativeSkillDisplay": {
            "type": "object",
            "required": [
                "goalScore",
                "personalScore"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "finalScore": {
                    "type": "integer"
                },
                "goalScore": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "leadGoalScore": {
                    "type": "integer"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "personalScore": {
                    "type": "integer"
                }
            }
        },
        "cycle.SkillLevel": {
            "type": "object",
            "required": [
                "level",
                "levelDescription"
            ],
            "properties": {
                "level": {
                    "type": "integer"
                },
                "levelDescription": {
                    "type": "string"
                }
            }
        },
        "cycle.UpdateGoalSkillsRequest": {
            "type": "object",
            "required": [
                "hardSkills"
            ],
            "properties": {
                "hardSkills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cycle.HardSkill"
                    }
                }
            }
        },
        "membersquad.SquadMember": {
            "type": "object",
            "properties": {
                "include": {
                    "type": "boolean"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/membersquad.UserAndRole"
                    }
                },
                "sqid": {
                    "type": "string"
                }
            }
        },
        "membersquad.UserAndRole": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "profile.RateSkill": {
            "type": "object",
            "properties": {
                "ratings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/profile.Rating"
                    }
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "profile.Rating": {
            "type": "object",
            "properties": {
                "score": {
                    "type": "integer"
                },
                "skid": {
                    "type": "string"
                }
            }
        },
        "profile.Skill": {
            "type": "object",
            "properties": {
                "score": {
                    "type": "integer"
                },
                "skid": {
                    "type": "string"
                }
            }
        },
        "profile.aboutme": {
            "type": "object",
            "properties": {
                "aboutMe": {
                    "type": "string"
                },
                "socialMedias": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "profile.mySkillRateInSquadResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/profile.Skill"
                    }
                }
            }
        },
        "skill.Skill": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "squad.AverageSkill": {
            "type": "object",
            "properties": {
                "average": {
                    "type": "number"
                },
                "skid": {
                    "type": "string"
                }
            }
        },
        "squad.SkillRating": {
            "type": "object",
            "properties": {
                "score": {
                    "type": "integer"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "squad.SkillRatings": {
            "type": "object",
            "properties": {
                "ratings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/squad.SkillRating"
                    }
                },
                "skid": {
                    "type": "string"
                }
            }
        },
        "squad.Squad": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "skillsRatings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/squad.SkillRatings"
                    }
                },
                "teamleadMail": {
                    "type": "string"
                }
            }
        },
        "squad.SquadAverageSkillOutput": {
            "type": "object",
            "properties": {
                "averagesSkill": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/squad.AverageSkill"
                    }
                },
                "squadId": {
                    "type": "string"
                }
            }
        },
        "squad.SquadFilter": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "user.GetEmailNameResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "user.GetSkillByUserIDResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.SkillNameScoreResponse"
                    }
                }
            }
        },
        "user.GetUserResponse": {
            "type": "object",
            "properties": {
                "aboutMe": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "employeeId": {
                    "type": "string"
                },
                "familyName": {
                    "type": "string"
                },
                "givenName": {
                    "type": "string"
                },
                "hardSkills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.MyHardSkill"
                    }
                },
                "jobRole": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "socialMedias": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "softSkills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.MySkill"
                    }
                },
                "squadId": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.MySquad"
                    }
                },
                "sub": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "technicalSkills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.MySkill"
                    }
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                }
            }
        },
        "user.MyHardSkill": {
            "type": "object",
            "properties": {
                "currentLevel": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "skilllevel": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.SkillLevel"
                    }
                },
                "sort": {
                    "type": "integer"
                }
            }
        },
        "user.MySkill": {
            "type": "object",
            "properties": {
                "score": {
                    "type": "integer"
                },
                "skid": {
                    "type": "string"
                }
            }
        },
        "user.MySquad": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string"
                },
                "sqid": {
                    "type": "string"
                }
            }
        },
        "user.SkillLevel": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "integer"
                },
                "leveldescription": {
                    "type": "string"
                }
            }
        },
        "user.SkillNameScoreResponse": {
            "type": "object",
            "properties": {
                "score": {
                    "type": "integer"
                },
                "skill": {
                    "$ref": "#/definitions/user.SkillResponse"
                }
            }
        },
        "user.SkillResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "Ariskill API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
